services:
  - type: web
    name: decrypttrace-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: AES_KEY
        value: decrypttrace_aes_key_must_be_32b!
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
